### ISSUE TITLE
Update the readme to show name

### ISSUE THREAD

**Issue by spsaroj** [spsaroj/storm-demo#2]

**Comment by 005sagar** [comment]
I already did it

**Comment by spsaroj** [comment]
I did it. Waiting for Susan to update it.
@susanmaharjan close this issue once done.

**Comment by susanmaharjan** [comment]
working on it.

**Comment by spsaroj** [comment]
@JingLi521864 needs to do it too.

**Comment by susanmaharjan** [comment]
done with adding name and sub topic
